### PR TITLE
Fix CLI tests

### PR DESCRIPTION
**Pull request by aminya**
This pull request:
- Fixes most of the CLI tests
- Adds TODO for the remaining failing ones (those who print an additional Unicode character)
- Bumps all dependencies except eslint/prettier ones (that means the tests are run against the latest dependencies)

### CODE REVIEW

**Comment by aminya** [comment]
@eventualbuddha After this, there are only a few failing tests remaining. 😃

**Comment by eventualbuddha** [comment]
Just so I understand, this is fixing the tests on Windows?

**Comment by aminya** [comment]
Yes mostly. Some happen on Linux too.

**Comment by eventualbuddha** [comment]
How do you reproduce the Linux ones? CI is passing just fine on the master branch: https://app.circleci.com/pipelines/github/decaffeinate/decaffeinate/1429/workflows/16e4aa21-4670-4fb3-a5d4-f93297897179/jobs/5875

**Comment by aminya** [comment]
This is the result of running the tests inside WSL. 

these fail due to the extra unicode char:
```js
 FAIL  test/cli_test.ts (684.665 s)
  ● decaffeinate CLI › properly modernizes a JS file

    assert.equal(received, expected)

    Expected value to be equal to:
      "import path from 'path';
    const b = 1;"
    Received:
      "import path from 'path';·
    "onst b = 1;

    Difference:

    - Expected
    + Received

    - import path from 'path';
    - const b = 1;
    + import path from 'path';
    + const b = 1;

      485 |     );
      486 |     const contents = readFileSync('./test_fixtures/F.tmp.js').toString();
    > 487 |     equal(
          |     ^
      488 |       stripSharedIndent(contents),
      489 |       stripSharedIndent(`
      490 |       import path from 'path';

      at Object.<anonymous> (test/cli_test.ts:487:5)

  ● decaffeinate CLI › discovers JS files with --modernize-js specified

    assert.equal(received, expected)

    Expected value to be equal to:
      "import path from 'path';
    const b = 1;"
    Received:
      "import path from 'path';·
    "onst b = 1;

    Difference:

    - Expected
    + Received

    - import path from 'path';
    - const b = 1;
    + import path from 'path';
    + const b = 1;

      509 |     );
      510 |     const contents = readFileSync('./test_fixtures/searchDir/F.js').toString();
    > 511 |     equal(
          |     ^
      512 |       stripSharedIndent(contents),
      513 |       stripSharedIndent(`
      514 |       import path from 'path';

      at Object.<anonymous> (test/cli_test.ts:511:5)

  ● decaffeinate CLI › recursively scans directories

    assert.equal(received, expected)

    Expected value to be equal to:
      "const a = 1;"
    Received:
      "const a = 1;·
    "

    Difference:

    - Expected
    + Received

    - const a = 1;
    + const a = 1;
    +

      528 |     );
      529 |     const contents = readFileSync('./test_fixtures/level1/level2/file.js').toString();
    > 530 |     equal(
          |     ^
      531 |       contents,
      532 |       stripSharedIndent(`
      533 |       const a = 1;

      at Object.<anonymous> (test/cli_test.ts:530:5)


Test Suites: 2 failed, 75 passed, 77 total
Tests:       4 failed, 1617 passed, 1621 total
Snapshots:   0 total
Time:        818.072 s
Ran all test suites.
```

this test fails due to indentation differences.
```js
 FAIL  test/conditional_test.ts (111.395 s)
  ● conditionals › creates a properly-formatted IIFE for nested `if`s in a function body

    expect(received).toBe(expected) // Object.is equality

    - Expected  - 3
    + Received  + 3

      a((() => {
    -   if (b) {
    +     if (b) {
          if (c) {
            return null;
    -     }
    +   }
    -   }
    + }
      })());

      63 |       actual = actual.substr(0, actual.length - 1);
      64 |     }
    > 65 |     expect(actual).toBe(expected);
         |                    ^
      66 |   } catch (err) {
      67 |     if (PatchError.detect(err)) {
      68 |       console.error(PatchError.prettyPrint(err));

      at checkOutput (test/support/check.ts:65:20)
      at Object.check [as default] (test/support/check.ts:17:3)
      at Object.<anonymous> (test/conditional_test.ts:544:10)
```

**Comment by aminya** [comment]
@eventualbuddha I expected you to merge this. Now I see a lot of conflicts are introduced

**Comment by eventualbuddha** [comment]
Probably not relevant anymore.

**Pull request closed without merging**
