### PR TITLE
chore: add a template for GitHub issues

### PR DESCRIPTION
**Pull request by eventualbuddha**
Does the instruction to uncomment the one you want make sense?

cc @alangpierce @Eden-Sun @an-sh @niieani @madskonradsen

### CODE REVIEW

**Comment by madskonradsen** [comment]
Yes! Wouldn't it be nice to have people create a REPL-link?

**Comment by niieani** [comment]
👍

**Comment by eventualbuddha** [comment]
@madskonradsen I added instructions for making a REPL link. Thanks for the suggestion!

**Comment by alangpierce** [comment]
👍 thanks

**Pull request merged**
