### PR TITLE
Add some tests for chain function calls.

### PR DESCRIPTION
**Pull request by lunks**
There are 3 tests, but only the first  of them is failing. The other 2 tests
are there just for the sake of clarity.

### CODE REVIEW

**Comment by lunks** [comment]
This is a failing test for #51.

**Comment by eventualbuddha** [comment]
I think this is pretty well covered now that the `patchers` branch has merged.

**Comment by lunks** [comment]
Confirmed it's working. I noticed you commented out a bunch of tests because it seems this is currently a WIP. I managed to narrow down a small chunk of CoffeScript that is currently failing. Is a similar PR with a failing test like this welcomed?

**Comment by eventualbuddha** [comment]
Yes please!

**Pull request closed without merging**
