### PR TITLE
fix: when patching an arg, don't write past the end of the call

### LINKED ISSUE #276: Line breaks in a statement within parentheses fail with: "AddVariableDeclarationsStage failed to parse" error
Breaking example:
```coffee
(a) ->
  (a not in b.map(a, (e) -> 
    e)
  )
```

The same code without the newline after `(e) ->` works:
```coffee
(a) ->
  (a not in b.map(a, (e) -> e)
  )
```

### LINKED ISSUE #370: Emits close-paren in the wrong place
decaffeinate is crashing on my CoffeeScript input:

```coffee
define [
], () ->

  somefunc 'something', ['something', (ContactService) ->
  
  ]
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=define%20%5B%0A%5D%2C%20()%20-%3E%0A%0A%20%20somefunc%20'something'%2C%20%5B'something'%2C%20(ContactService)%20-%3E%0A%20%20%0A%20%20%5D)
I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (6:5)
  4 |   return somefunc('something', ['something', function(ContactService) {}
  5 | 
> 6 |   ]);)
    |      ^
  7 | };```

### LINKED ISSUE #379: Returning 'expect to eql an array' throws AddVariableDeclarationsStage
decaffeinate is crashing on my CoffeeScript input:

```coffee
it "should foo", ->
  expect( bar ).to.eql [1]
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=it%20%22should%20foo%22%2C%20-%3E%0A%20%20expect(%20bar%20).to.eql%20%5B1%5D

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (2:35)
  1 | it("should foo", function() {
> 2 |   return expect( bar ).to.eql([1]);)
    |                                    ^
  3 | };
```

### LINKED ISSUE #405: Callback with object literal crashes
decaffeinate is crashing on my CoffeeScript input:

```coffee
Teacher.hasClass classId, () ->
  return cb null, {}
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=Teacher.hasClass%20classId%2C%20()%20-%3E%0A%20%20return%20cb%20null%2C%20%7B%7D%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (2:22)
  1 | Teacher.hasClass(classId, function() {
> 2 |   return cb(null, {});)
    |                       ^
  3 | };
  4 | 
```

### LINKED ISSUE #410: AddVariableDeclarationsStage failed to parse
decaffeinate is crashing on my CoffeeScript input:

```coffee
@server.on 'sioDisconnect', =>
	@_statuses = {}
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%40server.on%20'sioDisconnect'%2C%20%3D%3E%0A%09%40_statuses%20%3D%20%7B%7D

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (2:28)
  1 | this.server.on('sioDisconnect', () => {
> 2 | 	return this._statuses = {};)
    |                             ^
 3| };
```

### LINKED ISSUE #412: Callback arguments failed to parse
decaffeinate is crashing on my CoffeeScript input:

```coffee
_authenticate: (authKey, cb) ->
	@_getSession authKey, (err, {person, user, authKey, org} = {}) ->
		return cb null, {person, authKey, user, org}
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=_authenticate%3A%20(authKey%2C%20cb)%20-%3E%0A%09%40_getSession%20authKey%2C%20(err%2C%20%7Bperson%2C%20user%2C%20authKey%2C%20org%7D%20%3D%20%7B%7D)%20-%3E%0A%09%09return%20cb%20null%2C%20%7Bperson%2C%20authKey%2C%20user%2C%20org%7D%0A%0A

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (4:49)
  2 | 	_authenticate(authKey, cb) {
  3 | 		return this._getSession(authKey, function(err, {person, user, authKey, org} = {}) {
> 4 | 			return cb(null, {person, authKey, user, org});)
    |                                                  ^
  5 | 		};
  6 | 	}
```

### PR DESCRIPTION
**Pull request by alangpierce**
Closes #412
Closes #410
Closes #405
Closes #379
Closes #370
Closes #276

The `appendLineAfter` method was careful to never insert code past the end of
the current node's "bounding patcher", but the bounding patcher was computed in
a way that didn't work in all cases; it just found the lowest enclosing node
that's surrounded by parens. So in `f(a, b)`, the bounding patcher for `b` is
the whole expression, so there's nothing to stop `b` from inserting code past
the end of the close-paren. To fix, I made the bounding patcher code a little
smarter to recognize when it's traversing up a function call node and stop
there.

### CODE REVIEW

**Comment by madskonradsen** [comment]
NICE! This have really been one of the most annoying bugs of decaffeinate!!!! :)

**Comment by madskonradsen** [comment]
Holy moly! This (and probably the other PR's too) just took the project i'm working on from 448 files with errors to only 202 files with errors (checked with bulk-decaffeinate)!

**Comment by alangpierce** [comment]
Cool, glad to hear that! Do you know what the most common failures are in those 202 remaining issues? I have a fix for #397 (code in class bodies) that I'm hoping to get through soon, but beyond that, at least in my repo, it seems like a lot of smaller issues.

**Comment by madskonradsen** [comment]
Nice with #397 ! I didn't have the time to check the logs today, but will do it tomorrow morning, there might be some low-hanging fruit! But it could of course just be 202 strange corner cases that coffeescript in some way handles gracefully ;)

**Pull request merged**
